services:
  store:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.dev
    volumes:
      - static_volume:/usr/src/app/static
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - app-tier
  db:
    image: postgres:16.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=store
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    networks:
      - app-tier
  manage-database:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@store.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "16543:80"
    depends_on:
      - db
    networks:
      - app-tier
  web:
    build: 
      context: ./frontend
      dockerfile: ./nginx/Dockerfile
    volumes:
      - static_volume:/staticfiles
      - ./:/usr/src/app

    ports:
      - 1337:80
    depends_on:
      - store
    networks:
      - app-tier

volumes:
  postgres_data:
  static_volume:

networks:
  app-tier:
    driver: bridge
