# Generated by Django 4.2.13 on 2024-06-09 07:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('reason_cancelled', models.CharField(max_length=500, null=True)),
                ('total_price', models.FloatField(default=0.0)),
                ('total_quantity', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('CREATE', 'CREATE'), ('CANCELLED', 'CANCELLED'), ('SENT', 'SENT'), ('DELIVERED', 'DELIVERED')], default='CREATE')),
                ('delivered_on_time', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('delivered_total_days', models.IntegerField(default=0)),
                ('days_to_delivered', models.IntegerField(default=0)),
                ('paid_date', models.DateField(null=True)),
                ('real_paid_date', models.DateField(null=True)),
                ('delivered_date', models.DateField()),
                ('order_created_date', models.DateField()),
                ('real_delivered_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost', models.FloatField(default=0.0)),
                ('quantity', models.FloatField(default=0.0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
